-- Désactiver temporairement RLS sur les tables principales
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE merchants DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE carriers DISABLE ROW LEVEL SECURITY;
ALTER TABLE carrier_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE carrier_services DISABLE ROW LEVEL SECURITY;
ALTER TABLE carrier_zones DISABLE ROW LEVEL SECURITY;
ALTER TABLE carrier_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE carrier_allocation_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE shipments DISABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE return_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE return_inspections DISABLE ROW LEVEL SECURITY;
ALTER TABLE return_refunds DISABLE ROW LEVEL SECURITY;

-- Note: Les politiques RLS existantes sont conservées mais inactives
-- Pour réactiver le RLS plus tard, il suffira d'utiliser ENABLE ROW LEVEL SECURITY